version: '3'

services:
  migratedb-info:
    build: .
    command: -url=jdbc:mysql://14.225.241.239:33003/cms_dev?useSSL=false -user=cms_dev -password=cms_dev!@#456 -connectRetries=60 info
  migratedb-migrate:
    depends_on:
      - migratedb-info
    build: .
    command: -url=jdbc:mysql://14.225.241.239:33003/cms_dev?useSSL=false -user=cms_dev -password=cms_dev!@#456 -connectRetries=60 migrate