version: '3'
services:
  xbase_cms_backend:
    image: vunt/xbase_cms_backend:${GITHUB_SHA_SHORT}
    restart: always
    networks:
      - pronet

networks:
  pronet:
    external:
      name: pronet
