# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:
    branches: [ develop ]
    # paths:
    #   - 'service/**'
    #   - '.github/workflows/app-workflow.yaml'
  push:
    branches: [ develop ]
    # paths:
    #   - 'service/**'
    #   - '.github/workflows/app-workflow.yaml'

permissions:
  contents: read

jobs:
  project-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      working-directory: ./service/cms-service
      run: ./gradlew build -x test
    - uses: actions/upload-artifact@master
      with:
        name: xbase-cms-artifact
        path: ./service/cms-service/build/libs
      
  docker-build:
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    needs:
      - project-build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: xbase-cms-artifact
          path: ./service/cms-service/build/libs

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into the Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Step
        run: echo ${GITHUB_SHA::7}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./service/cms-service
          file: ./service/cms-service/Dockerfile
          push: true
          tags: |
            vunt/xbase_cms_backend:${{GITHUB_SHA::7}}
            vunt/xbase_cms_backend:latest

  deploy:
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    needs:
      - docker-build
    steps:
      - uses: actions/checkout@v3
      - name: Add Server key
        run: |
          touch ./service/cms-service/ci/dev/key.txt && echo "${{ secrets.SERVER_KEY }}" > ./service/cms-service/ci/dev/key.txt
          chmod 600 ./service/cms-service/ci/dev/key.txt
      - name: Deploy the application
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          GITHUB_SHA_SHORT: ${GITHUB_SHA::7}
        run: |
          set -e
          cd ./service/cms-service/ci/dev
          chmod +x deploy.sh
          ./deploy.sh
