name: Build & Delpoyment FE

on:
  pull_request:
    branches: [ develop ]
    paths:
      - 'ui/**'
      - '.github/workflows/fe.yml'
  push:
    branches: [ develop ]
    paths:
      - 'ui/**'
      - '.github/workflows/fe.yml'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build for production
        run: npm run build:prod
      - name: Deploy to production
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  
